# Generated by Django 5.2.7 on 2025-10-22 20:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AlumnoCita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=80)),
                ('apellido_paterno', models.CharField(max_length=80)),
                ('apellido_materno', models.CharField(max_length=80)),
                ('curp', models.CharField(max_length=18)),
                ('telefono', models.CharField(max_length=10)),
                ('celular', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=254)),
            ],
            options={
                'verbose_name': 'Alumno registrado en cita',
                'verbose_name_plural': 'Alumnos registrados en citas',
                'ordering': ['curp'],
            },
        ),
        migrations.CreateModel(
            name='Asuntos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=250)),
            ],
            options={
                'verbose_name': 'Asunto',
                'verbose_name_plural': 'Asuntos',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cve_estado', models.IntegerField(max_length=3)),
                ('nombre', models.CharField(max_length=80)),
            ],
            options={
                'verbose_name': 'Estado',
                'verbose_name_plural': 'Estados',
                'ordering': ['cve_estado'],
            },
        ),
        migrations.CreateModel(
            name='NivelEducativo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=80)),
            ],
            options={
                'verbose_name': 'Nivel Educativo',
                'verbose_name_plural': 'Niveles Educativos',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Municipio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cve_municipio', models.IntegerField(max_length=3)),
                ('nombre', models.CharField(max_length=80)),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tickets.estado')),
            ],
            options={
                'verbose_name': 'Municipio',
                'verbose_name_plural': 'Municipios',
                'ordering': ['cve_municipio'],
            },
        ),
        migrations.CreateModel(
            name='Cita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_interesado', models.CharField(max_length=250)),
                ('fecha_cita', models.DateTimeField()),
                ('fecha_creado', models.DateTimeField(auto_now_add=True)),
                ('alumno_cita', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tickets.alumnocita')),
                ('asunto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tickets.asuntos')),
                ('municipio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tickets.municipio')),
                ('nivel_educativo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tickets.niveleducativo')),
            ],
            options={
                'verbose_name': 'Cita',
                'verbose_name_plural': 'Citas',
                'ordering': ['-fecha_creado'],
            },
        ),
    ]
