# Generated by Django 5.2.7 on 2025-10-23 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estado',
            name='cve_estado',
            field=models.CharField(max_length=3),
        ),
        migrations.AlterField(
            model_name='municipio',
            name='cve_municipio',
            field=models.CharField(max_length=3),
        ),
    ]
